services:
  gui:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
      - /dev:/dev
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    network_mode: host
    restart: unless-stopped