version: '3'

services:
  gui:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    privileged: true
    network_mode: host 